Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.167.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Revenue By Appeal Category Code Forcast Add Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "6dfca468-e2c2-4c7d-98fd-ffb9f08e0f1d", "2b5fd8a8-c8cb-4d57-872e-d223695e5480", "Revenue By Appeal Category Code Forcast")>
Partial Public Class [RevenueByAppealCategoryCodeForcastAddDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _glfiscalyearid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of System.Guid)
    Private WithEvents _forecaststring As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _forecastdetails As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of RevenueByAppealCategoryCodeForcastAddDataFormFORECASTDETAILSUIModel)

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public Sub New()
        MyBase.New()

        _glfiscalyearid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of System.Guid)
        _forecaststring = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _forecastdetails = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of RevenueByAppealCategoryCodeForcastAddDataFormFORECASTDETAILSUIModel)

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New System.Guid("6dfca468-e2c2-4c7d-98fd-ffb9f08e0f1d")
        MyBase.DataFormInstanceId = New System.Guid("2b5fd8a8-c8cb-4d57-872e-d223695e5480")
        MyBase.RecordType = "Revenue By Appeal Category Code Forcast"
        MyBase.HideBackgroundPanel = True
        MyBase.FORMHEADER.Value = "Add a revenue by appeal category code forcast"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/customconfigurationsetting/RevenueByAppealCategoryCodeForcastAddDataForm.html"

        '
        '_glfiscalyearid
        '
        _glfiscalyearid.Name = "GLFISCALYEARID"
        _glfiscalyearid.Caption = "Fiscal Year"
        _glfiscalyearid.Required = True
        _glfiscalyearid.SimpleDataListId = New System.Guid("8bf288a8-7c0f-4213-8b15-474f5868712f")
        _glfiscalyearid.BlankValueCaption = "Select Fiscal Year"
        Me.Fields.Add(_glfiscalyearid)
        '
        '_forecaststring
        '
        _forecaststring.Name = "FORECASTSTRING"
        _forecaststring.Caption = "Forcast string"
        _forecaststring.Required = True
        Me.Fields.Add(_forecaststring)
        '
        '_forecastdetails
        '
        _forecastdetails.Name = "FORECASTDETAILS"
        _forecastdetails.Caption = "Revenue forecast by appeal category code"
        _forecastdetails.Required = True
        _forecastdetails.DBReadOnly = True
        Me.Fields.Add(_forecastdetails)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Fiscal Year
    ''' </summary>
    <System.ComponentModel.Description("Fiscal Year")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [GLFISCALYEARID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of System.Guid)
        Get
            Return _glfiscalyearid
        End Get
    End Property
    
    ''' <summary>
    ''' Forcast string
    ''' </summary>
    <System.ComponentModel.Description("Forcast string")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [FORECASTSTRING]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _forecaststring
        End Get
    End Property
    
    ''' <summary>
    ''' Revenue forecast by appeal category code
    ''' </summary>
    <System.ComponentModel.Description("Revenue forecast by appeal category code")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.167.0")> _
    Public ReadOnly Property [FORECASTDETAILS]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of RevenueByAppealCategoryCodeForcastAddDataFormFORECASTDETAILSUIModel)
        Get
            Return _forecastdetails
        End Get
    End Property
    
End Class
